# 不同环境不同连接信息(我做了脱敏, 请换成自己真实的)
host:
  redis: ${redis.host}
  mysql: ${db.host}
password:
  redis: ${redis.password}
  mysql: ${db.password}
username:
  mysql:  ${db.username}

datasource:
  driver: com.mysql.cj.jdbc.Driver
  prefix: jdbc:mysql

# 生产环境中不要开启Druid的removeAbandoned配置
open:
  removeAbandoned: false

#线程池配置
executor:
  pool:
    corePoolSize: 16
    maxPoolSize: 16
    queueCapacity: 200
    keepAliveSeconds: 0