# 不同环境不同连接信息(我做了脱敏, 请换成自己真实的)
host:
  redis: ${redis.host}
  mysql: ${db.host}
password:
  redis: ${redis.password}
  mysql: ${db.password}
username:
  mysql:  ${db.username}

datasource:
  driver: com.p6spy.engine.spy.P6SpyDriver
  prefix: jdbc:p6spy:mysql

open:
  removeAbandoned: true

#线程池配置
executor:
  pool:
    corePoolSize: 8
    maxPoolSize: 8
    queueCapacity: 200
    keepAliveSeconds: 0