server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true


spring:
  profiles:
    # 环境
    active: @profileActive@
  # 视图配置
  mvc:
    static-path-pattern: /static/**
  # 网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
    suffix: .ftl
    cache: false
  # 文件上传的最大值
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # 数据库连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host.mysql}/admin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${username.mysql}
    password: ${password.mysql}
    druid:
      validationQuery: SELECT 1
      initialSize: 5
      minIdle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  #redis配置
  redis:
    database: 12
    host: ${host.redis}
    port: 6379
    password: ${password.redis}
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5       # 连接池中的最大空闲连接
        max-idle: 10      # 连接池中的最小空闲连接


# mybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.someget.admin.common.sys.dal.entity, com.someget.admin.dal.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
#    metaObjectHandler: com.someget.admin.common.config.SysMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false